#TUKANO USER E SHORTS
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tukano-user-shorts-app
  labels:
    app: tukano-user-shorts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tukano-user-shorts
  template:
    metadata:
      labels:
        app: tukano-user-shorts
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: user-shorts-container
          image: grave1/tukano-users-shorts-1:latest
          ports:
            - containerPort: 8080
          env:
            - name: BLOBS_URL
              value: "http://scc2425-grave1-tukano-blobs-1.germanywestcentral.azurecontainer.io:8081/tukano-blobs-1/rest/users"
            - name: SECRET
              value: "SEGREDO_BEM_GUARDADINHO"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: tukano-user-shorts-service
spec:
  selector:
    app: tukano-user-shorts
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
---

#TUKANO BLOBS
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tukano-blobs-app
  labels:
    app: tukano-blobs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tukano-blobs
  template:
    metadata:
      labels:
        app: tukano-blobs
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: blobs-container
          image: grave1/tukano-blobs-1:latest
          ports:
            - containerPort: 8082
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /
              port: 8082
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: tukano-blobs-service
spec:
  selector:
    app: tukano-blobs
  ports:
    - protocol: TCP
      port: 82
      targetPort: 8082
  type: LoadBalancer
